openapi: 3.1.0
info:
  title: FOOD ORDERING APP
  description: Restaurant & Menu Service based on the OpenAPI 3.0 specification .
  version: 1.0.0
  contact: 
    email: mansizti18@gmail.com
    url: "https://sample.dev"

servers:
  - url: http://localhost:3001/api/v1
    description: localhost version restaurant-menu service url  

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  

paths:
  /restaurant/register:
     post:
      tags:
        - Restaurant
      summary: Register restaurant if you are owner
      security:
        - bearerAuth: []  
      consumes:
        - application/json
      produces:
        - application/json  
      requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  name:
                     type: string
                  profile:
                     type: file
                     format: image/png, image/jpeg
                  email:
                     type: string       
                  address:
                     type: string
                  lat:
                     type: string  
                  long:
                     type: string
  
      responses:
        '200': #status code
          description: Register Restaurant
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string
                  profile_url:
                    type: URL
                  restaurant:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      profile:
                        type: string
                      address:
                        type: string
                      lat: 
                        type: string
                      long:
                        type: string
                      created_by:
                        type: string
                      updated_by:
                        type: string                      
        400:
          description: Bad request
        500:
          description: internal server error              
        

  /restaurant:
    get:
      tags:
        - Restaurant
      summary: Get All Restaurant
      security:
        - bearerAuth: [] 
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The number of items page
        - in: query
          name: search
          schema:
            type: string  
        - in: query
          name: sort
          schema:
            type: boolean
          description: true or false
        - in: query
          name: sortBy
          schema:
            type: string     
        - in: query
          name: sortType
          schema:
            type: string      
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurants:
                    type: Array
                    items: 
                      type: object
                      properties:
                        id:
                          type: string
                        name: 
                          type: string
                        email:
                          type: string
                        profile:
                          type: string
                        address:
                          type: string
                        lat:
                          type: string
                        long:
                          type: string
                        created_by:
                          type: string
                        updated_by: 
                          type: string          
        400:
          description: Bad request
        500:
          description: internal server error        
  
  /restaurant/update/{id}:
     patch:
      tags:
        - Restaurant
      security:
        - bearerAuth: []  
      summary: Update Restaurant Details by Owner
      parameters:
        - name: id
          in: path
          required: true
          default: 1
          schema:
            type: string
      consumes:
        - application/json
      produces:
        - application/json  
      requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  name:
                     type: string
                  profile:
                     type: file
                     format: image/png, image/jpeg
                  email:
                     type: string       
                  address:
                     type: string
                  lat:
                     type: integer  
                  long:
                     type: integer            
      responses:
        '200': #status code
          description: Update the restaurant details 
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string               
        400:
          description: Bad request
        500:
          description: internal server error   

  /restaurant/delete/{id}:
     delete:
      tags:
        - Restaurant
      security:
        - bearerAuth: []  
      summary: Delete Restaurant Details by Owner
      parameters:
        - name: id
          in: path
          required: true
          default: 1
          schema:
            type: string
      consumes:
        - application/json
      produces:
        - application/json            
      responses:
        '200': #status code
          description: Delete the restaurant details 
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string               
        400:
          description: Bad request
        500:
          description: internal server error          

  /restaurant/{itemId}:
    get:
      tags:
        - Internals
      summary: Get All Restaurant
      parameters:
        - name: itemId
          in: path
          required: true
          default: 1
          schema:
            type: string
      security:
        - bearerAuth: []  
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurant_id:
                    type: string
                             
        400:
          description: Bad request
        500:
          description: internal server error        


  /menu/add:
     post:
      tags:
        - Menu
      summary: Add Menu in Restaurant Menu Table
      security:
        - bearerAuth: []  
      consumes:
        - application/json
      produces:
        - application/json  
      requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  restaurant_id:
                    type: integer
                  category_id:
                    type: integer
                  dish_name:
                    type: string       
                  description:
                    type: string
                  price:
                    type: string  
                  sub_category_id:
                    type: integer
  
      responses:
        '200': #status code
          description: Register Restaurant Menu
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string
                  restaurant_menu:
                    type: object
                    properties:
                      id:
                        type: string
                      category_id:
                        type: string
                      restaurant_id:
                        type: string
                      dish_name:
                        type: string
                      description:
                        type: string
                      price: 
                        type: string
                      createdby:
                        type: string
                      updatedby:
                        type: string
                      createdat:
                        type: string 
                      updatedat:     
                        type: string
                      sub_category_id:
                        type: string                     
        400:
          description: Bad request
        500:
          description: internal server error        

  /menu:
    get:
      tags:
        - Menu
      summary: Get All Restaurant-Menu
      security:
        - bearerAuth: []  
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The number of items page
        - in: query
          name: search
          schema:
            type: string  
        - in: query
          name: sort
          schema:
            type: boolean
          description: true or false
        - in: query
          name: sortBy
          schema:
            type: string     
        - in: query
          name: sortType
          schema:
            type: string
        - in: query
          name: restaurant_id
          schema:
            type: integer
        - in: query
          name: category_id
          schema:
            type: integer
        - in: query
          name: sub_category_id
          schema:
            type: integer               
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  Menu:
                    type: Array
                    items: 
                      type: object
                      properties:
                        id:
                          type: string
                        dish_name: 
                          type: string
                        price:
                          type: string          
        400:
          description: Bad request
        500:
          description: internal server error        

  /menu/{id}:
    get:
      tags:
        - Menu
      summary: Get Menu By ID
      parameters:
        - name: id
          in: path
          required: true
          default: 1
          schema:
            type: string
      security:
        - bearerAuth: []  
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  Item:
                    type: Array
                    items: 
                      type: object
                      properties:
                        id:
                          type: string
                        category_id: 
                          type: string
                        restaurant_id:
                          type: string
                        dish_name:
                          type: string
                        description:
                          type: string
                        price:
                          type: string
                        createdby:
                          type: string
                        updatedby:
                          type: string
                        createdat: 
                          type: string
                        updatedat:
                          type: string
                        sub_category_id:
                          type: string    
                             
        400:
          description: Bad request
        500:
          description: internal server error         

  /menu/update/{id}:
     patch:
      tags:
        - Menu
      security:
        - bearerAuth: []  
      summary: Update Menu Details by Owner
      parameters:
        - name: id
          in: path
          required: true
          default: 1
          schema:
            type: string
      consumes:
        - application/json
      produces:
        - application/json  
      requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  restaurant_id:
                     type: integer
                  category_id:
                     type: integer
                  dish_name:
                     type: string       
                  description:
                     type: string
                  price:
                     type: decimal  
                  sub_category_id:
                     type: integer            
      responses:
        '200': #status code
          description: Update the menu details 
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string               
        400:
          description: Bad request
        500:
          description: internal server error   

  /menu/delete/{id}:
     delete:
      tags:
        - Menu
      security:
        - bearerAuth: []  
      summary: Delete Menu Details by Owner
      parameters:
        - name: id
          in: path
          required: true
          default: 1
          schema:
            type: string
      consumes:
        - application/json
      produces:
        - application/json            
      responses:
        '200': #status code
          description: Delete the menu details 
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  message:
                    type: string               
        400:
          description: Bad request
        500:
          description: internal server error                